"""Add organizational structure models

Revision ID: 3e2f8a1e210f
Revises: 16e98cc34425
Create Date: 2025-06-23 05:25:48.984924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2f8a1e210f'
down_revision: Union[str, None] = '16e98cc34425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_organization_id', 'departments', ['organization_id'], unique=False)
    op.create_index('idx_departments_parent_id', 'departments', ['parent_id'], unique=False)
    op.create_index('idx_departments_path', 'departments', ['path'], unique=False)
    op.create_table('org_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_org_roles_organization_code')
    )
    op.create_index('idx_org_roles_organization_id', 'org_roles', ['organization_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employees_organization_id', 'employees', ['organization_id'], unique=False)
    op.create_index('idx_employees_user_id', 'employees', ['user_id'], unique=False)
    op.create_index('uq_employees_organization_operator', 'employees', ['organization_id', 'operator_id'], unique=True, postgresql_where=sa.text('operator_id IS NOT NULL'))
    op.create_table('department_employee_org_roles',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('org_role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_role_id'], ['org_roles.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'employee_id', 'org_role_id', name='pk_department_employee_org_roles')
    )
    op.create_index('idx_department_employee_org_roles_department_id', 'department_employee_org_roles', ['department_id'], unique=False)
    op.create_index('idx_department_employee_org_roles_employee_id', 'department_employee_org_roles', ['employee_id'], unique=False)
    op.create_index('idx_department_employee_org_roles_org_role_id', 'department_employee_org_roles', ['org_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_department_employee_org_roles_org_role_id', table_name='department_employee_org_roles')
    op.drop_index('idx_department_employee_org_roles_employee_id', table_name='department_employee_org_roles')
    op.drop_index('idx_department_employee_org_roles_department_id', table_name='department_employee_org_roles')
    op.drop_table('department_employee_org_roles')
    op.drop_index('uq_employees_organization_operator', table_name='employees', postgresql_where=sa.text('operator_id IS NOT NULL'))
    op.drop_index('idx_employees_user_id', table_name='employees')
    op.drop_index('idx_employees_organization_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('idx_org_roles_organization_id', table_name='org_roles')
    op.drop_table('org_roles')
    op.drop_index('idx_departments_path', table_name='departments')
    op.drop_index('idx_departments_parent_id', table_name='departments')
    op.drop_index('idx_departments_organization_id', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
